using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DhanSutra.Models
{
    public class PurchaseInvoiceDto
    {
        public long PurchaseId { get; set; } = 0; // 0 for new
        public string InvoiceNo { get; set; }
        public long InvoiceNum { get; set; }
        public string InvoiceDate { get; set; } // "yyyy-MM-dd"
        public long SupplierId { get; set; }
        public SupplierDraftDto SupplierDraft { get; set; }
        public decimal SubTotal { get; set; }
        public decimal TotalAmount { get; set; }
        public decimal TotalTax { get; set; }
        public decimal RoundOff { get; set; }
        public string Notes { get; set; }
        public string CreatedBy { get; set; }
        public string PaymentMode { get; set; }

        public decimal PaidAmount { get; set; }

        public decimal BalanceAmount { get; set; }
        public string PaidVia { get; set; } 


        public List<PurchaseInvoiceItemDto> Items { get; set; } = new List<PurchaseInvoiceItemDto>();
    }

    public class PurchaseInvoiceItemDto
    {
        public long PurchaseItemId { get; set; } = 0; // For loading existing invoices

        public long ItemId { get; set; }
        public string ItemName { get; set; }
        public string HsnCode { get; set; }
        public decimal Qty { get; set; }
        public decimal Rate { get; set; }
        public decimal DiscountPercent { get; set; }
        public decimal NetRate { get; set; }

        public decimal GstPercent { get; set; }
        public decimal GstValue { get; set; }
        public decimal CgstPercent { get; set; }
        public decimal CgstValue { get; set; }
        public decimal SgstPercent { get; set; }
        public decimal SgstValue { get; set; }

        public decimal IgstPercent { get; set; }
        public decimal IgstValue { get; set; }

        public decimal LineSubTotal { get; set; }       // Qty * NetRate
        public decimal LineTotal { get; set; }  // Amount + GST
        public string Notes { get; set; }       

        // ★ NEW (auto-generated by backend)
        public int BatchNum { get; set; }         // e.g., 1,2,3
        public string BatchNo { get; set; }       // e.g., ITEMCODE-B1

        // OPTIONAL extra batch metadata (stored in PurchaseItemDetails)
        public decimal? SalesPrice { get; set; }
        public decimal? Mrp { get; set; }
        public string Description { get; set; }
        public string MfgDate { get; set; }
        public string ExpDate { get; set; }
        public string ModelNo { get; set; }
        public string Brand { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public decimal? Weight { get; set; }
        public string Dimension { get; set; }
        public decimal AvailableQty { get; set; }

    }


}
